version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    restart: unless-stopped
    ports:
      - "9092:9091"
    environment:
      - NODE_ENV=production
      - TARGET=${TARGET}
      - EXTENSION_TARGET=${EXTENSION_TARGET}
      - EMBED_HOST=${EMBED_HOST}
      - AUTH_SECRET_TOKEN2=${AUTH_SECRET_TOKEN2}
      - AUTH_SECRET_TOKEN=${AUTH_SECRET_TOKEN}